name: CI/CD supermartech

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Configuration JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          cache-path: ~/.m2
          
      # Exécution des tests avec Maven
      - name: Test with Maven
        run: mvn clean test

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run build
