package com.supermatech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageProAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageProAllPropertiesEquals(ImagePro expected, ImagePro actual) {
        assertImageProAutoGeneratedPropertiesEquals(expected, actual);
        assertImageProAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageProAllUpdatablePropertiesEquals(ImagePro expected, ImagePro actual) {
        assertImageProUpdatableFieldsEquals(expected, actual);
        assertImageProUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageProAutoGeneratedPropertiesEquals(ImagePro expected, ImagePro actual) {
        assertThat(expected)
            .as("Verify ImagePro auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageProUpdatableFieldsEquals(ImagePro expected, ImagePro actual) {
        assertThat(expected)
            .as("Verify ImagePro relevant properties")
            .satisfies(e -> assertThat(e.getImgP_Path()).as("check imgP_Path").isEqualTo(actual.getImgP_Path()))
            .satisfies(e -> assertThat(e.getPro_id()).as("check pro_id").isEqualTo(actual.getPro_id()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageProUpdatableRelationshipsEquals(ImagePro expected, ImagePro actual) {
        assertThat(expected)
            .as("Verify ImagePro relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
